before_install:
- openssl aes-256-cbc -K $encrypted_e501b24d39c6_key -iv $encrypted_e501b24d39c6_iv
  -in tests/testthat/salesforcer.tar.enc -out tests/testthat/salesforcer.tar -d
- tar xvf tests/testthat/salesforcer.tar -C tests/testthat
- R -q -e 'install.packages(c("remotes", "curl", "RForcecom")); remotes::install_github("ropenscilabs/tic");
  tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: travis_wait 30 R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
language: r
sudo: false
dist: xenial
cache: packages
latex: false
matrix:
  include:
  - r: oldrel
  - r: release
    env:
    - BUILD_PKGDOWN: true
  - r: devel
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - secure: zKVrcOUJzH/CDXE8/72+D2a+BGjLPfnbeuJDi/js/mkaD5+dWr3waXaBH1azUtL1eSwxvafaHdrgE1Q+mTb7opBXoXQhEDFOm0NqQ8ZqlfJWYibb3vhtVjP9rtfx+C8XMyodgidzq6yNAlJoKK2krGxVzYCnwEn1g7kkY61NKcNFAIJ4/xHMpP7F7jIBGwejN2Ws3S4M+0sKQzYdeCSS65jtVEXj8bkfB5MEejVnf2laJzNm2CWCEN/Q5wHZFspSKyN+Ii+bD6MUFwv2R7pmfptdZfpraA6WQTD7g8I4NLDcs49Abm4yVdWdjhDZOXSHMCfY1illGzUYY4WCA0LYhh2wVzz+fAa2c9C9uTtSUpKToXdggzcZFah4IZaAJ0daHTCHuDU1mE27aKpYrucmibhlcdI2yNQZJyX9jkr1bXdgJXPUwi89pIPTdQwj/VqJOG/bQl1EHf7wn0IRyD5suEVP3OxbZE2Xfzxn8y3WrYmTTG5KKi+3Bf2/ATyzk/98zfX+FPQOjJerimhnxevzFwNuIFhfXKl+0sJQnCzo2H7WtKSz13AmNsA8S+x3081wMNDtScm4p0UgkbxHT3iJx8w4i7carW7gPKP911GPegq5RImAmOJBvITWas8VHrl3G66g/NaxgbRCqIktRjHCjSK25AmBQjzw0j6w9SUaj9A=
  - secure: qHti6gWCLkzBcgQtseFLRaJGhR3Zacsr83k83rtMl5FF4AmAVgpmSK8MLhlMKsZ3kabSLyHW6YgGzm7rSCGOxpI62WkXinWGeyaGHNwvsP0ugsq3p09nxA16wUFEiNDRxgeEs7sMnlOeOQ8GwUU1LAzC6+XxRtVYqDNy5JDX5dSpL2apOTP8SqAQUfgk+UiFREizu6ldg5+lWTDXq4B9S3bEPk+VkVZZWUz/9YiZVBH4MUklsKJWaBq0JMPHA4DnBA4TY3Qu/ts4rZima/ecVJdnHmAzH5eRVWaUQRTLKrEzsq29iz8emg6J6UGzp4KSo+hkTNMcaTfdwj3xg8C0sQNC3KR3YJIqoquYgyDXDDziNTKfGUNbvRFBKZi22X2VesuuwdPe/5XJbrrA7hoY9w1XdcU4czlhBT8/MB82vudZTZh+0maoNNKF/rwjn3OgGASI/4niOq455uqq34fqgP3enpV4ME94dndCcJ4OF6Xl4Pv05jYxAfrd7cSpXCe8FMWw9RjBFVQnhbif6L4g6vmWEMNlpTP24DdW/ag6SWsZsFE4xn7luavrnnaAZqT0rDrwyhkJU7XWSfh3c7OBhFo41hbI66LnVgmebZ3dNWeZ9QGstWOeAa6Oeupftrmt494gnYkXlkEUd8O08ymg3XnuOReEVnXN5IQ/iyQ9vpY=
  - secure: NIUic5TLnEsbDj8BCM4+x0cQHYIcl3zDnhU1s3oixo6OdjA/yyK1JiVvmF1JCFOgweRhz+m0I5DBng2rhcsakFkOg2P58lxDcvn99fGIa5BVTcQwkQyfRkzEPeesqUhJoUXYkIr3ebrVdU2RXE95dOBVMo2YNmPROY3xzNJm1bSjzP4sLz6TPAMYDDpkYPhznKsq7IhcjZRazQpYQzQrwSILGg4Wdr5e1SRdof3e8x6yLDmtvsNJMU7PAE82/ioDpbuwy8rCb6fQ/gT4a0tLDKrkff5JIT5CUIWtl7nGF11lR0z4teSydpRYsYmMhOXsMmx3n8rquwdZ8AxBXBxWsKx4RZgViq+/yNVR6fRcQO3WOGFN7zpWb2yMrtfnrhXeiHrYZp+50QN+tilY6o0ut5cP/JTaELKYbc/UCKM1W8GbrPxWdIcAqFjYoBqk2DqnLBybjor4ZQt4MED7SXMk/TOuBrJMy5VhDpXFuYREv+oi0m1q0OMY6s6ZrjxRl6QVwshHYP02fbd7g3VdA6IJJ6C7ez3Z+jXwp/c/+x7cPwp86EPiEqGrSx338wmmeEvwWiny0ymQe+AHeIN7gukatxwyZkTd7qoEAaf3e1MwhlwzYebVUvWk+hbafriuXf22QosKlmIwcmtBFl0nzteIrFqE7NIRwIhEsctc8o9hE1I=
services:
