name: Build pkgdown site

on:
  push:
    branches: main
      
jobs:
  pkgdown:

    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SALESFORCER_USERNAME: ${{ secrets.SALESFORCER_USERNAME }}
      SALESFORCER_PASSWORD: ${{ secrets.SALESFORCER_PASSWORD }}
      SALESFORCER_SECURITY_TOKEN: ${{ secrets.SALESFORCER_SECURITY_TOKEN }}     
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Reveal env vars
        run: |
          echo GITHUB_WORKFLOW   = $GITHUB_WORKFLOW
          echo HOME              = $HOME
          echo GITHUB_ACTION     = $GITHUB_ACTION
          echo GITHUB_ACTIONS    = $GITHUB_ACTIONS
          echo GITHUB_ACTOR      = $GITHUB_ACTOR
          echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
          echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE  = $GITHUB_WORKSPACE
          echo GITHUB_SHA        = $GITHUB_SHA
          echo GITHUB_REF        = $GITHUB_REF      
      
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
          
      - uses: r-lib/actions/setup-pandoc@v1
    
      - name: Query dependencies
        run: |
          # getting dev remotes for better behaviour re: installation order
          install.packages("https://github.com/r-lib/remotes/archive/master.tar.gz", repos = NULL)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
    
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-2-
      
      - name: Install dependencies
        run: |
          # temporary hack until there's a macOS binary for ps
          install.packages("ps", type = "source")        
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}
    
      - name: Install package
        run: R CMD INSTALL .
    
      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'        
          
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: StevenMMortimer/salesforcer
          event-type: main-02-test-coverage
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          
      - name: Set final R-CMD-check status
        if: failure()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: StevenMMortimer/salesforcer
          event-type: main-06-R-CMD-check-final
          client-payload: '{"success": false}'
