name: Build pkgdown site

on:
  repository_dispatch:
    types: [build_success]
      
jobs:
  pkgdown:

    # see https://github.com/lewagon/quay-github-actions-dispatch for use-case
    if: startsWith(github.sha, github.event.client_payload.text)
  
    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SALESFORCER_USERNAME: ${{ secrets.SALESFORCER_USERNAME }}
      SALESFORCER_PASSWORD: ${{ secrets.SALESFORCER_PASSWORD }}
      SALESFORCER_SECURITY_TOKEN: ${{ secrets.SALESFORCER_SECURITY_TOKEN }}     
    
    steps:
      - uses: actions/checkout@v2
      
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          ref: main # can be commit SHA or tag too
          check-name: test-coverage # name of the existing check
          repo-token: ${{ env.GITHUB_PAT }}
          wait-interval: 60 # seconds
      
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
          
      - uses: r-lib/actions/setup-pandoc@master
    
      - name: Query dependencies
        run: |
          # getting dev remotes for better behaviour re: installation order
          install.packages("https://github.com/r-lib/remotes/archive/master.tar.gz", repos = NULL)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
    
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-2-
      
      - name: Install dependencies
        run: |
          # temporary hack until there's a macOS binary for ps
          install.packages("ps", type = "source")        
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}
    
      - name: Install package
        run: R CMD INSTALL .
    
      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'        
